### ISSUE TITLE
Write tOracleInput with an sdo_Geometry into Shapefile

### ISSUE THREAD

**Issue by jkutterer** [talend-spatial/talend-spatial#58]
Write tOracleInput into Shapefile

I've tried to read a OracleDb-Table with an sdo_geometry using the tOracleInput. When I tried to write the db table as an shapefile with sShapefileOutput (tOracleInput ---->  sShapefileOutput) I get the following error message:

```
Exception in thread "main" java.lang.Error: Unresolved compilation problem:
    Type mismatch: cannot convert from Object to Geometry
    at etl_test.db2db_spatial_0_1.db2db_spatial.tOracleInput_1Process(db2db_spatial.java:901)
    at etl_test.db2db_spatial_0_1.db2db_spatial.runJobInTOS(db2db_spatial.java:1296)
    at etl_test.db2db_spatial_0_1.db2db_spatial.main(db2db_spatial.java:1161)
```

In the tOracleInput I have to select Object as Type (geoemtry don't work) and as DB Type I select MDSYS.SDO_GEOMETRY

In the sshapefileOutput if selected geometry as type.

**Comment by OlivierBArr** [comment]
still no answer ?
I have the same !
