### ISSUE TITLE
Missing dependency declarations for GeometryOperation and GeometryUtility routines

### ISSUE THREAD

**Issue by jonescc** [talend-spatial/talend-spatial#75]
I sometimes get build errors due to missing dependencies for these routines.

In particular, GeometryOperation is missing the gt-api-8.5.jar dependency required for org.geotools.geometry.jts.JTS and GeometryUtility is missing the required gt-xsd-gml3-8.5.jar dependency for org.geotools.gml3.GMLConfiguration in org.talend.sdi.designer.routines-7.0.1/plugin.xml.

Not sure why in some jobs I don't get errors for these missing dependencies, but they look to me to be required.

```
!MESSAGE Application error
!STACK 1
org.talend.commons.exception.PersistenceException: org.talend.designer.runprocess.ProcessorException: Routines "GeometryOperation" has compile errors
Error Line: 156
Detail Message: org.geotools.geometry.jts cannot be resolved
	at org.talend.repository.ui.wizards.exportjob.scriptsmanager.BuildJobManager.buildJob(BuildJobManager.java:298)
	at au.org.emii.talend.codegen.Generator.exportJob(Generator.java:169)
	at au.org.emii.talend.codegen.Generator.start(Generator.java:134)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

**Comment by fxprunayre** [comment]
Hi Craig, 

> Not sure why in some jobs I don't get errors for these missing dependencies, but they look to me to be required.

It may be related to the presence of components in your job which also depends on those. And then the dependency is resolved.

Thanks for the fix.
