### ISSUE TITLE
org.talend.designer.runprocess.ProcessorException: Routines "GeometryOperation" has compile errors

### ISSUE THREAD

**Issue by LaurenBassett** [talend-spatial/talend-spatial#86]
I am using macOS Catalina 10.15.4 , Talend DI 7.3.1, and this extension, and when I try to run the spatial demo, I get the following error: 
`org.talend.designer.runprocess.ProcessorException: Routines "GeometryOperation" has compile errors
Error Line: 1
Detail Message: The type org.opengis.referencing.crs.CoordinateReferenceSystem cannot be resolved. It is indirectly referenced from required .class files
	at org.talend.designer.runprocess.JobErrorsChecker.checkRoutinesCompilationError(JobErrorsChecker.java:434)
	at org.talend.designer.runprocess.JobErrorsChecker.checkLastGenerationHasCompilationError(JobErrorsChecker.java:373)
	at org.talend.designer.runprocess.DefaultRunProcessService.checkLastGenerationHasCompilationError(DefaultRunProcessService.java:539)
	at org.talend.designer.runprocess.RunProcessService.checkLastGenerationHasCompilationError(RunProcessService.java:317)
	at org.talend.designer.runprocess.ProcessorUtilities.generateBuildInfo(ProcessorUtilities.java:955)
	at org.talend.designer.runprocess.ProcessorUtilities.generateCode(ProcessorUtilities.java:615)
	at org.talend.designer.runprocess.ProcessorUtilities.generateCode(ProcessorUtilities.java:2068)
	at org.talend.designer.runprocess.RunProcessContext$1.run(RunProcessContext.java:601)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:440)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:356)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:474)
	at org.eclipse.ui.internal.progress.ProgressMonitorJobsDialog.run(ProgressMonitorJobsDialog.java:240)
	at org.eclipse.ui.internal.progress.ProgressManager.run(ProgressManager.java:966)
	at org.talend.designer.runprocess.RunProcessContext.exec(RunProcessContext.java:548)
	at org.talend.designer.runprocess.ui.ProcessComposite.exec(ProcessComposite.java:1448)
	at org.talend.designer.runprocess.ui.views.ProcessView$RunAction.run(ProcessView.java:700)
	at org.talend.designer.runprocess.ui.actions.RunProcessAction.run(RunProcessAction.java:63)
	at org.talend.designer.core.debug.JobLaunchConfigurationDelegate$1$1.run(JobLaunchConfigurationDelegate.java:98)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4095)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3762)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.talend.rcp.intro.Application.start(Application.java:280)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
`

What should I do?

**Comment by LaurenBassett** [comment]
I tried to update the plugin.xml file from here, but it still will not compile. 
https://github.com/talend-spatial/talend-spatial/commit/9b68aebb04dea2438334a5222fc32d75f53536ed#diff-5d0708c48423ba296e53174edabe5bef

**Comment by baradwaj87** [comment]
I tried your resolution and the above error was fixed. However, I received another error indicating that the "org.opengis.referencing.crs.FactoryException" cannot be resolved. I fixed this by adding the following library to the plugin xml file. This resolved the issue for me.

"gt-opengis-22-RC.jar"

Thanks!
Sharat
www.cimt.nl

**Comment by nagyrobir** [comment]
Could anybody please help me with what version can be used, and which combinations of versions work, or how can this be made to work, cause i am in constant struggle. Thank you a lot!
